import MainLayout from '../Layouts/MainLayout';
import { useForm } from '@inertiajs/react';
import { sports } from '../ronisiContent';
export default function Registration(){
 const {data,setData,post,processing,errors,reset} = useForm({name:'',email:'',phone:'',team_name:'',organization:'',sports:[],participants_count:1,notes:''});
 const toggle = s => setData('sports', data.sports.includes(s) ? data.sports.filter(x=>x!==s) : [...data.sports, s]);
 const submit = e => {e.preventDefault(); post('/pieteiksanas', {onSuccess:()=>reset()});};
 return <MainLayout><section className="mx-auto max-w-4xl px-4 py-14 lg:px-8"><p className="font-bold tracking-[0.35em] text-cyan-300">PIETEIKŠANĀS</p><h1 className="mt-5 text-5xl font-black">Pieteikuma forma</h1><form onSubmit={submit} className="mt-10 grid gap-5 rounded-3xl border border-white/10 bg-white/5 p-6"><Input label="Vārds, uzvārds" value={data.name} onChange={v=>setData('name',v)} error={errors.name}/><Input label="E-pasts" value={data.email} onChange={v=>setData('email',v)} error={errors.email}/><Input label="Telefons" value={data.phone} onChange={v=>setData('phone',v)}/><Input label="Komandas nosaukums" value={data.team_name} onChange={v=>setData('team_name',v)}/><Input label="Organizācija / fakultāte" value={data.organization} onChange={v=>setData('organization',v)}/><label className="font-bold">Sporta veidi</label><div className="grid gap-3 sm:grid-cols-2">{sports.map(s=><button type="button" key={s} onClick={()=>toggle(s)} className={`rounded-xl border px-4 py-3 text-left ${data.sports.includes(s)?'border-cyan-300 bg-cyan-300/20':'border-white/10 bg-white/5'}`}>{s}</button>)}</div>{errors.sports&&<p className="text-red-300">{errors.sports}</p>}<Input label="Dalībnieku skaits" type="number" value={data.participants_count} onChange={v=>setData('participants_count',v)} error={errors.participants_count}/><label className="font-bold">Piezīmes</label><textarea className="rounded-xl border border-white/10 bg-slate-950 p-3" rows="5" value={data.notes} onChange={e=>setData('notes',e.target.value)} /><button disabled={processing} className="rounded-xl bg-cyan-300 px-6 py-3 font-black text-slate-950">Nosūtīt pieteikumu</button></form></section></MainLayout>
}
function Input({label,value,onChange,error,type='text'}){return <div><label className="font-bold">{label}</label><input type={type} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 p-3" value={value} onChange={e=>onChange(e.target.value)} />{error&&<p className="mt-1 text-red-300">{error}</p>}</div>}
