export const migratedImages = [
  '/images/plakats.png',
  '/images/karogs.jpg',
  '/images/map.jpg',
  '/images/redbull.png',
  '/images/1.jpg',
  '/images/2.jpg',
  '/images/3.jpg',
  '/images/4.jpg',
  '/images/5.jpg',
  '/images/6.jpg',
  '/images/7.jpg',
  '/images/8.jpg',
  '/images/9.jpg',
  '/images/10.jpg',
  '/images/11.jpg',
  '/images/12.jpg',
  '/images/13.jpg',
  '/images/14.jpg',
  '/images/15.jpg',
  '/images/16.jpg',
  '/images/17.jpg',
  '/images/18.jpg',
  '/images/19.jpg',
  '/images/20.jpg',
  '/images/21.jpg',
  '/images/22.jpg',
  '/images/23.jpg',
  '/images/24.jpg',
];

export const pageImages = {
  home: migratedImages[0],
  news: migratedImages[0],
  preparation: migratedImages[1],
  about: migratedImages[4],
  supporters: migratedImages[3],
  organizers: migratedImages[5],
  registration: migratedImages[6],
  lunch: migratedImages[7],
  lodging: migratedImages[8],
  schedule: migratedImages[9],
  area: migratedImages[2],
  sports: migratedImages[10],
  gallery: migratedImages[11],
  faq: migratedImages[12],
  contacts: migratedImages[13],
};

export const imagePool = migratedImages;
